### ISSUE TITLE
I think the trial website is broken?

### ISSUE THREAD

**Issue by MandyMeindersma** [arizzitano/css3wordart#2]
![image](https://user-images.githubusercontent.com/17459171/56612990-e3bf1880-65d2-11e9-8517-4203bc619bb2.png)
These are the errors I got.

I tried to click yes AND hell yes but nothing happened.

**Comment by arizzitano** [comment]
Hi @MandyMeindersma! You're right -- the library was originally built to use [Object.observe](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) way back in 2014, but that language feature has been deprecated. Probably the quickest solution is to add a polyfill or shim like [this one](https://github.com/MaxArt2501/object-observe). I'll go ahead and do that (unless you want to give it a shot!) Thanks for reporting.

**Comment by MandyMeindersma** [comment]
I won't have that much time to look into it but once you make a pr I would love to look it over and see what you did. Thank you so much! Happy coding!

**Comment by arizzitano** [comment]
After some struggle, I believe I got it working again :) http://arizzitano.github.io/css3wordart/

**Comment by MandyMeindersma** [comment]
It works for me! Thanks!
